const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCHING_ERROR: "PROFILE_DATA_FETCHING_ERROR",
    DATA_EDIT: "PROFILE_DATA_EDIT",
  },
};

export { actions };
